drop table if exists t_comment;

drop table if exists t_dream;

drop table if exists t_group;

drop table if exists t_user;

drop table if exists t_user_group;

CREATE TABLE t_user (
  id BIGINT generated by default as identity,
  email VARCHAR(100) NOT NULL unique,
  password VARCHAR(100) NOT NULL,
  nickname VARCHAR(100),
  salt VARCHAR(64) NOT NULL,
  status TINYINT DEFAULT 0,
  type TINYINT DEFAULT 0,
  register_date TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
);

CREATE TABLE t_dream (
  id BIGINT generated by default as identity,
  name varchar(100) DEFAULT NULL,
  content CLOB,
  c_num INT DEFAULT NULL,
  u_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (u_id) REFERENCES t_user (id)
);

CREATE TABLE t_comment (
  id BIGINT generated by default as identity,
  content varchar(255),
  reply_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_id BIGINT,
  d_id BIGINT,
  primary key (id),
  FOREIGN KEY (u_id) REFERENCES t_user (id),
  FOREIGN KEY (d_id) REFERENCES t_dream (id)
);

CREATE TABLE t_group (
  id INT generated by default as identity,
  name varchar(100) DEFAULT NULL,
  d_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (d_id) REFERENCES t_dream (id)
);

CREATE TABLE t_user_group (
  u_id BIGINT DEFAULT NULL,
  g_id BIGINT DEFAULT NULL,
  primary key (u_id, g_id),
  FOREIGN KEY (u_id) REFERENCES t_user (id),
  FOREIGN KEY (g_id) REFERENCES t_group (id)
);

